<?xml version="1.0" encoding="UTF-8"?>
<fpmd:simulation xmlns:fpmd="http://www.quantum-simulation.org/ns/fpmd/fpmd-1.0">

                   ============================
                   I qbox 1.63.2              I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I http://qboxcode.org      I
                   ============================


<release> 1.63.2 dell </release>
<sysname> Linux </sysname>
<nodename> theobook68 </nodename>
<start_time> 2016-04-06T12:24:32Z </start_time>
<mpi_processes count="4">
<process id="0"> theobook68 </process>
<process id="1"> theobook68 </process>
<process id="2"> theobook68 </process>
<process id="3"> theobook68 </process>
</mpi_processes>
[qbox] <cmd>load ../h2ogs/test.xml</cmd>
 LoadCmd: loading from ../h2ogs/test.xml
 XMLGFPreprocessor: reading from ../h2ogs/test.xml size: 3959423
 XMLGFPreprocessor: read time: 0.001403
 XMLGFPreprocessor: local read rate: 672.8 MB/s  aggregate read rate: 2691 MB/s
 XMLGFPreprocessor: tag fixing time: 0.004905
 XMLGFPreprocessor: segment definition time: 0.01786
 XMLGFPreprocessor: boundary adjustment time: 0.006786
 XMLGFPreprocessor: transcoding time: 0.002632
 XMLGFPreprocessor: data redistribution time: 0.003089
 XMLGFPreprocessor: XML compacting time: 0.0003228
 XMLGFPreprocessor: total time: 0.03778
 xmlcontent.size(): 274407
 Starting XML parsing

 species oxygen:
<species name="oxygen">
 <description>
 PSGen-1.6.0 pseudopotential: HSCV O xc=PBE
 Generated by PSGen-1.6.0 on 2009-02-15T02:25:11Z
 psgen arguments:
 -element O -xc PBE -smooth_v -bound l=0:rc=0.8 -bound l=1:rc=0.8
 </description>
 <symbol>O</symbol>
 <atomic_number>8</atomic_number>
 <mass>16</mass>
 <norm_conserving_pseudopotential>
 <valence_charge>6</valence_charge>
 <lmax>1</lmax>
 <llocal>1</llocal>
 <nquad>0</nquad>
 <rquad>0</rquad>
 <mesh_spacing>0.01</mesh_spacing>
 </norm_conserving_pseudopotential>
</species>
 Kleinman-Bylander potential
 rcps_ =   1.5

 species hydrogen:
<species name="hydrogen">
 <description>
 PSGen-1.6.0 pseudopotential: HSCV H xc=PBE
 Generated by PSGen-1.6.0 on 2009-02-15T02:24:50Z
 psgen arguments:
 -element H -xc PBE -smooth_v -bound l=0:rc=0.5
 </description>
 <symbol>H</symbol>
 <atomic_number>1</atomic_number>
 <mass>1.008</mass>
 <norm_conserving_pseudopotential>
 <valence_charge>1</valence_charge>
 <lmax>0</lmax>
 <llocal>0</llocal>
 <nquad>0</nquad>
 <rquad>0</rquad>
 <mesh_spacing>0.01</mesh_spacing>
 </norm_conserving_pseudopotential>
</species>
 local potential
 rcps_ =   1.5
 WavefunctionHandler::startElement: wavefunction nspin=1 nel=8 nempty=0
 WavefunctionHandler::startElement: slater_determinant
 kpoint=0 0 0 weight=1 size=4
 WavefunctionHandler::endElement: slater_determinant
 XML parsing done
 SampleReader: read time: 0.09887 s
[qbox] <cmd>set wf_dyn PSDA</cmd>
[qbox] <cmd>set ecutprec 5</cmd>
[qbox] [qbox] <cmd>set atoms_dyn CG</cmd>
[qbox] <cmd>run 20 10</cmd>
  EnergyFunctional: np0v,np1v,np2v: 90 90 90
  EnergyFunctional: vft->np012(): 729000
<wavefunction ecut="35" nspin="1" nel="8" nempty="0">
<cell a="16.000000 0.000000 0.000000"
      b="0.000000 16.000000 0.000000"
      c="0.000000 0.000000 16.000000"/>
 reciprocal lattice vectors
 0.392699 0.000000 0.000000
 0.000000 0.392699 0.000000
 0.000000 0.000000 0.392699
<refcell a="0.000000 0.000000 0.000000"
         b="0.000000 0.000000 0.000000"
         c="0.000000 0.000000 0.000000"/>
<grid nx="44" ny="44" nz="44"/>
 kpoint: 0.000000 0.000000 0.000000 weight: 1.000000
<slater_determinant kpoint="0.000000 0.000000 0.000000" size="4">
 sdcontext: 4x1
 basis size: 20242
 c dimensions: 20332x4   (5083x4 blocks)
 <density_matrix form="diagonal" size="4">
 </density_matrix>
</slater_determinant>
</wavefunction>
<iteration count="1">
  total_electronic_charge: 8.00000000
  <ekin>        12.38728117 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.24241225 </eps>
  <enl>          1.98631320 </enl>
  <ecoul>       -7.11063042 </ecoul>
  <exc>         -4.09253807 </exc>
  <esr>          1.47178349 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07198637 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07198637 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> 0.00000000 0.00000000 0.00000000 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.01316231 -0.00000493 0.00000936 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.12800000 1.44400000 0.00000000 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00659212 0.00905256 -0.00004123 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.12800000 -1.44400000 0.00000000 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00654360 -0.00894733 -0.00002179 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07198637 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 1.00000000
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.01520590 </eigenvalue_sum>
  <etotal_int>     -17.06725122 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.02735156 </eigenvalue_sum>
  Anderson extrapolation: theta=1.34790961 (1.34790961)
  <etotal_int>     -17.07018842 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04170084 </eigenvalue_sum>
  Anderson extrapolation: theta=0.05074071 (0.05074071)
  <etotal_int>     -17.07210486 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04218894 </eigenvalue_sum>
  Anderson extrapolation: theta=1.50350230 (1.50350230)
  <etotal_int>     -17.07217534 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04293222 </eigenvalue_sum>
  Anderson extrapolation: theta=0.13315444 (0.13315444)
  <etotal_int>     -17.07221971 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04311080 </eigenvalue_sum>
  Anderson extrapolation: theta=1.86551132 (1.86551132)
  <etotal_int>     -17.07222302 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04354553 </eigenvalue_sum>
  Anderson extrapolation: theta=0.23114674 (0.23114674)
  <etotal_int>     -17.07222703 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04372146 </eigenvalue_sum>
  Anderson extrapolation: theta=1.38098183 (1.38098183)
  <etotal_int>     -17.07222814 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04399479 </eigenvalue_sum>
  Anderson extrapolation: theta=0.26726605 (0.26726605)
  <etotal_int>     -17.07222912 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04408106 </eigenvalue_sum>
  Anderson extrapolation: theta=1.55673732 (1.55673732)
  <etotal_int>     -17.07222932 </etotal_int>
  <timing name="iteration" min="    1.369" max="    1.369"/>
</iteration>
<iteration count="2">
  total_electronic_charge: 8.00000000
  <ekin>        12.34534092 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.15685731 </eps>
  <enl>          1.99137079 </enl>
  <ecoul>       -7.16876201 </ecoul>
  <exc>         -4.08332191 </exc>
  <esr>          1.42479169 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07222952 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07222952 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01316231 -0.00000493 0.00000936 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00099942 0.00004638 -0.00000357 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13459212 1.45305256 -0.00004123 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00072484 0.00191138 -0.00001021 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13454360 -1.45294733 -0.00002179 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00075889 -0.00195186 -0.00000613 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07222952 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 1.00000000
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04341363 </eigenvalue_sum>
  <etotal_int>     -17.07222579 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04357097 </eigenvalue_sum>
  Anderson extrapolation: theta=1.48244874 (1.48244874)
  <etotal_int>     -17.07222938 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04381459 </eigenvalue_sum>
  Anderson extrapolation: theta=0.06651841 (0.06651841)
  <etotal_int>     -17.07223198 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04383960 </eigenvalue_sum>
  Anderson extrapolation: theta=2.01318873 (2.00000000)
  <etotal_int>     -17.07223210 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04388955 </eigenvalue_sum>
  Anderson extrapolation: theta=0.20065216 (0.20065216)
  <etotal_int>     -17.07223222 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04389714 </eigenvalue_sum>
  Anderson extrapolation: theta=1.86370227 (1.86370227)
  <etotal_int>     -17.07223224 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04390568 </eigenvalue_sum>
  Anderson extrapolation: theta=0.28177863 (0.28177863)
  <etotal_int>     -17.07223227 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04390309 </eigenvalue_sum>
  Anderson extrapolation: theta=1.70333142 (1.70333142)
  <etotal_int>     -17.07223228 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04389603 </eigenvalue_sum>
  Anderson extrapolation: theta=0.42855420 (0.42855420)
  <etotal_int>     -17.07223229 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04389195 </eigenvalue_sum>
  Anderson extrapolation: theta=1.48089904 (1.48089904)
  <etotal_int>     -17.07223230 </etotal_int>
  <timing name="iteration" min="    1.377" max="    1.378"/>
</iteration>
<iteration count="3">
  total_electronic_charge: 8.00000000
  <ekin>        12.34480936 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.15530856 </eps>
  <enl>          1.99134979 </enl>
  <ecoul>       -7.16989987 </ecoul>
  <exc>         -4.08318302 </exc>
  <esr>          1.42379691 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07223230 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07223230 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01265978 0.00004202 0.00000472 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00157801 -0.00001998 -0.00000003 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13456474 1.45393096 -0.00004674 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00073366 0.00174680 -0.00000112 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13455580 -1.45387821 -0.00002543 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00072794 -0.00174002 -0.00000081 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07223230 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 2.10000000
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04301609 </eigenvalue_sum>
  <etotal_int>     -17.07222676 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04320151 </eigenvalue_sum>
  Anderson extrapolation: theta=1.48648051 (1.48648051)
  <etotal_int>     -17.07223131 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04349642 </eigenvalue_sum>
  Anderson extrapolation: theta=0.05325498 (0.05325498)
  <etotal_int>     -17.07223452 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04353029 </eigenvalue_sum>
  Anderson extrapolation: theta=1.67497000 (1.67497000)
  <etotal_int>     -17.07223462 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04359532 </eigenvalue_sum>
  Anderson extrapolation: theta=0.14835169 (0.14835169)
  <etotal_int>     -17.07223470 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04360961 </eigenvalue_sum>
  Anderson extrapolation: theta=1.90394985 (1.90394985)
  <etotal_int>     -17.07223470 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04363476 </eigenvalue_sum>
  Anderson extrapolation: theta=0.21180401 (0.21180401)
  <etotal_int>     -17.07223471 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04363742 </eigenvalue_sum>
  Anderson extrapolation: theta=1.56293874 (1.56293874)
  <etotal_int>     -17.07223472 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04363898 </eigenvalue_sum>
  Anderson extrapolation: theta=0.31600272 (0.31600272)
  <etotal_int>     -17.07223472 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04363761 </eigenvalue_sum>
  Anderson extrapolation: theta=1.68772708 (1.68772708)
  <etotal_int>     -17.07223472 </etotal_int>
  <timing name="iteration" min="    1.523" max="    1.524"/>
</iteration>
<iteration count="4">
  total_electronic_charge: 8.00000000
  <ekin>        12.34400058 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.15337320 </eps>
  <enl>          1.99131242 </enl>
  <ecoul>       -7.17120525 </ecoul>
  <exc>         -4.08296926 </exc>
  <esr>          1.42270223 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07223472 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07223472 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01210700 0.00009365 -0.00000039 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00139139 -0.00007078 0.00000024 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13453462 1.45489720 -0.00005280 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00068970 0.00151948 -0.00000027 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13456922 -1.45490219 -0.00002945 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00063759 -0.00145357 -0.00000020 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07223472 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 4.41000000
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04179435 </eigenvalue_sum>
  <etotal_int>     -17.07220343 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04218935 </eigenvalue_sum>
  Anderson extrapolation: theta=1.48407149 (1.48407149)
  <etotal_int>     -17.07222339 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04280782 </eigenvalue_sum>
  Anderson extrapolation: theta=0.05397286 (0.05397286)
  <etotal_int>     -17.07223746 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04287776 </eigenvalue_sum>
  Anderson extrapolation: theta=1.69771222 (1.69771222)
  <etotal_int>     -17.07223793 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04301298 </eigenvalue_sum>
  Anderson extrapolation: theta=0.15254565 (0.15254565)
  <etotal_int>     -17.07223826 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04304261 </eigenvalue_sum>
  Anderson extrapolation: theta=1.89284296 (1.89284296)
  <etotal_int>     -17.07223829 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04309393 </eigenvalue_sum>
  Anderson extrapolation: theta=0.20964573 (0.20964573)
  <etotal_int>     -17.07223834 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04309881 </eigenvalue_sum>
  Anderson extrapolation: theta=1.53818282 (1.53818282)
  <etotal_int>     -17.07223835 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04310087 </eigenvalue_sum>
  Anderson extrapolation: theta=0.30702151 (0.30702151)
  <etotal_int>     -17.07223836 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04309768 </eigenvalue_sum>
  Anderson extrapolation: theta=1.67646493 (1.67646493)
  <etotal_int>     -17.07223837 </etotal_int>
  <timing name="iteration" min="    1.492" max="    1.493"/>
</iteration>
<iteration count="5">
  total_electronic_charge: 8.00000000
  <ekin>        12.34236074 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.14934593 </eps>
  <enl>          1.99121247 </enl>
  <ecoul>       -7.17393771 </ecoul>
  <exc>         -4.08252793 </exc>
  <esr>          1.42040198 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07223837 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07223837 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01094616 0.00020209 -0.00001111 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00117833 -0.00019881 0.00000126 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13447136 1.45692630 -0.00006552 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00060195 0.00104761 -0.00000010 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13459740 -1.45705254 -0.00003787 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00045328 -0.00085897 -0.00000006 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07223837 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 4.41000000
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.02904610 </eigenvalue_sum>
  <etotal_int>     -17.07131416 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.03336842 </eigenvalue_sum>
  Anderson extrapolation: theta=1.35560270 (1.35560270)
  <etotal_int>     -17.07185142 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.03882545 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04945043 (0.04945043)
  <etotal_int>     -17.07220374 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.03903391 </eigenvalue_sum>
  Anderson extrapolation: theta=1.52214672 (1.52214672)
  <etotal_int>     -17.07221653 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.03936276 </eigenvalue_sum>
  Anderson extrapolation: theta=0.13030185 (0.13030185)
  <etotal_int>     -17.07222463 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.03943615 </eigenvalue_sum>
  Anderson extrapolation: theta=1.88458859 (1.88458859)
  <etotal_int>     -17.07222522 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.03961331 </eigenvalue_sum>
  Anderson extrapolation: theta=0.22071503 (0.22071503)
  <etotal_int>     -17.07222593 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.03968190 </eigenvalue_sum>
  Anderson extrapolation: theta=1.37311078 (1.37311078)
  <etotal_int>     -17.07222612 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.03978871 </eigenvalue_sum>
  Anderson extrapolation: theta=0.25278210 (0.25278210)
  <etotal_int>     -17.07222628 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.03982187 </eigenvalue_sum>
  Anderson extrapolation: theta=1.57155670 (1.57155670)
  <etotal_int>     -17.07222631 </etotal_int>
  <timing name="iteration" min="    1.444" max="    1.444"/>
</iteration>
<iteration count="6">
  total_electronic_charge: 8.00000000
  <ekin>        12.32609359 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.11628402 </eps>
  <enl>          1.99326148 </enl>
  <ecoul>       -7.19636292 </ecoul>
  <exc>         -4.07893448 </exc>
  <esr>          1.40225806 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07222634 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07222634 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01655883 -0.00071355 -0.00000169 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00356347 0.00080299 -0.00000062 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13714863 1.46081870 -0.00006138 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00199138 -0.00205878 0.00000008 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13658628 -1.46006958 -0.00003510 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00138344 0.00128834 0.00000003 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07222634 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 1.13202786
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04971337 </eigenvalue_sum>
  <etotal_int>     -17.07173761 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04701678 </eigenvalue_sum>
  Anderson extrapolation: theta=1.35814727 (1.35814727)
  <etotal_int>     -17.07203368 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04316808 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04854374 (0.04854374)
  <etotal_int>     -17.07222803 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04296935 </eigenvalue_sum>
  Anderson extrapolation: theta=1.54197517 (1.54197517)
  <etotal_int>     -17.07223505 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04264165 </eigenvalue_sum>
  Anderson extrapolation: theta=0.13060661 (0.13060661)
  <etotal_int>     -17.07223956 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04257522 </eigenvalue_sum>
  Anderson extrapolation: theta=1.89251588 (1.89251588)
  <etotal_int>     -17.07223989 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04242375 </eigenvalue_sum>
  Anderson extrapolation: theta=0.21333900 (0.21333900)
  <etotal_int>     -17.07224028 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04237205 </eigenvalue_sum>
  Anderson extrapolation: theta=1.35425605 (1.35425605)
  <etotal_int>     -17.07224038 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04229413 </eigenvalue_sum>
  Anderson extrapolation: theta=0.23772322 (0.23772322)
  <etotal_int>     -17.07224046 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04227185 </eigenvalue_sum>
  Anderson extrapolation: theta=1.56316612 (1.56316612)
  <etotal_int>     -17.07224047 </etotal_int>
  <timing name="iteration" min="    1.478" max="    1.478"/>
</iteration>
<iteration count="7">
  total_electronic_charge: 8.00000000
  <ekin>        12.33820762 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.14088580 </eps>
  <enl>          1.99176506 </enl>
  <ecoul>       -7.17970820 </ecoul>
  <exc>         -4.08161916 </exc>
  <esr>          1.41572434 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224049 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224049 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01238691 -0.00003295 -0.00000869 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00009242 0.00003204 0.00000034 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13515860 1.45792547 -0.00006446 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00004741 0.00026089 -0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13510794 -1.45782700 -0.00003716 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00000619 -0.00031435 -0.00000000 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224049 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 1.13202786
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04207678 </eigenvalue_sum>
  <etotal_int>     -17.07224037 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04211461 </eigenvalue_sum>
  Anderson extrapolation: theta=1.44670090 (1.44670090)
  <etotal_int>     -17.07224052 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04217376 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04954292 (0.04954292)
  <etotal_int>     -17.07224062 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04218049 </eigenvalue_sum>
  Anderson extrapolation: theta=1.71651234 (1.71651234)
  <etotal_int>     -17.07224062 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04219407 </eigenvalue_sum>
  Anderson extrapolation: theta=0.19547284 (0.19547284)
  <etotal_int>     -17.07224063 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04219795 </eigenvalue_sum>
  Anderson extrapolation: theta=2.32598882 (2.00000000)
  <etotal_int>     -17.07224063 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04220536 </eigenvalue_sum>
  Anderson extrapolation: theta=0.52647488 (0.52647488)
  <etotal_int>     -17.07224063 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04220828 </eigenvalue_sum>
  Anderson extrapolation: theta=0.86254654 (0.86254654)
  <etotal_int>     -17.07224063 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04220958 </eigenvalue_sum>
  Anderson extrapolation: theta=0.62441979 (0.62441979)
  <etotal_int>     -17.07224063 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04220932 </eigenvalue_sum>
  Anderson extrapolation: theta=0.76592723 (0.76592723)
  <etotal_int>     -17.07224063 </etotal_int>
  <timing name="iteration" min="    1.337" max="    1.337"/>
</iteration>
<iteration count="8">
  total_electronic_charge: 8.00000000
  <ekin>        12.33802146 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.14048589 </eps>
  <enl>          1.99174764 </enl>
  <ecoul>       -7.17995604 </ecoul>
  <exc>         -4.08156780 </exc>
  <esr>          1.41552308 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224063 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224063 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01232765 0.00003006 -0.00000858 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00007574 -0.00002115 0.00000004 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13502676 1.45810715 -0.00006459 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00004027 0.00023427 -0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13504286 -1.45809476 -0.00003724 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00005424 -0.00021672 0.00000000 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224063 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 2.37725850
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04202941 </eigenvalue_sum>
  <etotal_int>     -17.07224045 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04206811 </eigenvalue_sum>
  Anderson extrapolation: theta=1.41917881 (1.41917881)
  <etotal_int>     -17.07224062 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04212618 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04809014 (0.04809014)
  <etotal_int>     -17.07224073 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04213161 </eigenvalue_sum>
  Anderson extrapolation: theta=1.66743370 (1.66743370)
  <etotal_int>     -17.07224073 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04214190 </eigenvalue_sum>
  Anderson extrapolation: theta=0.15054256 (0.15054256)
  <etotal_int>     -17.07224073 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04214416 </eigenvalue_sum>
  Anderson extrapolation: theta=1.87393223 (1.87393223)
  <etotal_int>     -17.07224073 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04214818 </eigenvalue_sum>
  Anderson extrapolation: theta=0.23179472 (0.23179472)
  <etotal_int>     -17.07224073 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04214878 </eigenvalue_sum>
  Anderson extrapolation: theta=1.48118432 (1.48118432)
  <etotal_int>     -17.07224073 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04214930 </eigenvalue_sum>
  Anderson extrapolation: theta=0.29381023 (0.29381023)
  <etotal_int>     -17.07224073 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04214918 </eigenvalue_sum>
  Anderson extrapolation: theta=1.52147784 (1.52147784)
  <etotal_int>     -17.07224073 </etotal_int>
  <timing name="iteration" min="    1.475" max="    1.476"/>
</iteration>
<iteration count="9">
  total_electronic_charge: 8.00000000
  <ekin>        12.33788282 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.14010734 </eps>
  <enl>          1.99172411 </enl>
  <ecoul>       -7.18021376 </ecoul>
  <exc>         -4.08152656 </exc>
  <esr>          1.41530169 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224073 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224073 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01226246 0.00009937 -0.00000846 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00009781 -0.00010975 0.00000002 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13488173 1.45830700 -0.00006474 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00001540 0.00021966 -0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13497128 -1.45838929 -0.00003734 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00009793 -0.00011493 0.00000000 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224073 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 4.99224285
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04177267 </eigenvalue_sum>
  <etotal_int>     -17.07223957 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04185547 </eigenvalue_sum>
  Anderson extrapolation: theta=1.41977327 (1.41977327)
  <etotal_int>     -17.07224031 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04198012 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04864645 (0.04864645)
  <etotal_int>     -17.07224080 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04199225 </eigenvalue_sum>
  Anderson extrapolation: theta=1.68615934 (1.68615934)
  <etotal_int>     -17.07224082 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201547 </eigenvalue_sum>
  Anderson extrapolation: theta=0.15475295 (0.15475295)
  <etotal_int>     -17.07224083 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04202068 </eigenvalue_sum>
  Anderson extrapolation: theta=1.88931461 (1.88931461)
  <etotal_int>     -17.07224083 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203001 </eigenvalue_sum>
  Anderson extrapolation: theta=0.23745836 (0.23745836)
  <etotal_int>     -17.07224083 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203145 </eigenvalue_sum>
  Anderson extrapolation: theta=1.49045380 (1.49045380)
  <etotal_int>     -17.07224083 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203273 </eigenvalue_sum>
  Anderson extrapolation: theta=0.30162965 (0.30162965)
  <etotal_int>     -17.07224083 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203246 </eigenvalue_sum>
  Anderson extrapolation: theta=1.51411716 (1.51411716)
  <etotal_int>     -17.07224083 </etotal_int>
  <timing name="iteration" min="    1.371" max="    1.372"/>
</iteration>
<iteration count="10">
  total_electronic_charge: 8.00000000
  <ekin>        12.33757241 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.13930095 </eps>
  <enl>          1.99168521 </enl>
  <ecoul>       -7.18076003 </ecoul>
  <exc>         -4.08143747 </exc>
  <esr>          1.41483671 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224083 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224083 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01212557 0.00024492 -0.00000821 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00012885 -0.00029775 0.00000000 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13457717 1.45872668 -0.00006505 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00003731 0.00019164 -0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13482096 -1.45900780 -0.00003753 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00018811 0.00009473 0.00000001 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224083 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 4.99224285
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04197357 </eigenvalue_sum>
  <etotal_int>     -17.07218027 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04192590 </eigenvalue_sum>
  Anderson extrapolation: theta=1.38576887 (1.38576887)
  <etotal_int>     -17.07221541 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04186893 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04748900 (0.04748900)
  <etotal_int>     -17.07223875 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04188889 </eigenvalue_sum>
  Anderson extrapolation: theta=1.55735936 (1.55735936)
  <etotal_int>     -17.07223954 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04192745 </eigenvalue_sum>
  Anderson extrapolation: theta=0.12866501 (0.12866501)
  <etotal_int>     -17.07224005 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04193612 </eigenvalue_sum>
  Anderson extrapolation: theta=1.93056646 (1.93056646)
  <etotal_int>     -17.07224009 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04194959 </eigenvalue_sum>
  Anderson extrapolation: theta=0.20827932 (0.20827932)
  <etotal_int>     -17.07224013 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04194888 </eigenvalue_sum>
  Anderson extrapolation: theta=1.41299437 (1.41299437)
  <etotal_int>     -17.07224015 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04194508 </eigenvalue_sum>
  Anderson extrapolation: theta=0.25765462 (0.25765462)
  <etotal_int>     -17.07224016 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04194222 </eigenvalue_sum>
  Anderson extrapolation: theta=1.64508687 (1.64508687)
  <etotal_int>     -17.07224016 </etotal_int>
  <timing name="iteration" min="    1.383" max="    1.383"/>
</iteration>
<iteration count="11">
  total_electronic_charge: 8.00000000
  <ekin>        12.33796810 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.13956411 </eps>
  <enl>          1.99139507 </enl>
  <ecoul>       -7.18057774 </ecoul>
  <exc>         -4.08146148 </exc>
  <esr>          1.41491312 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224016 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224016 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01120514 -0.00094681 -0.00000767 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00015454 0.00097798 -0.00000001 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13414676 1.46053321 -0.00006573 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00031572 -0.00056145 0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13357751 -1.45978728 -0.00003789 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00041368 -0.00036638 -0.00000001 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224016 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 1.32403118
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04194207 </eigenvalue_sum>
  <etotal_int>     -17.07220872 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201012 </eigenvalue_sum>
  Anderson extrapolation: theta=1.38499685 (1.38499685)
  <etotal_int>     -17.07222764 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04206570 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04770569 (0.04770569)
  <etotal_int>     -17.07224021 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04204814 </eigenvalue_sum>
  Anderson extrapolation: theta=1.56750940 (1.56750940)
  <etotal_int>     -17.07224063 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201469 </eigenvalue_sum>
  Anderson extrapolation: theta=0.12938220 (0.12938220)
  <etotal_int>     -17.07224091 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200785 </eigenvalue_sum>
  Anderson extrapolation: theta=1.90733266 (1.90733266)
  <etotal_int>     -17.07224093 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04199751 </eigenvalue_sum>
  Anderson extrapolation: theta=0.20115303 (0.20115303)
  <etotal_int>     -17.07224096 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04199822 </eigenvalue_sum>
  Anderson extrapolation: theta=1.38791356 (1.38791356)
  <etotal_int>     -17.07224096 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200135 </eigenvalue_sum>
  Anderson extrapolation: theta=0.24417175 (0.24417175)
  <etotal_int>     -17.07224097 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200358 </eigenvalue_sum>
  Anderson extrapolation: theta=1.64735780 (1.64735780)
  <etotal_int>     -17.07224097 </etotal_int>
  <timing name="iteration" min="    1.352" max="    1.353"/>
</iteration>
<iteration count="12">
  total_electronic_charge: 8.00000000
  <ekin>        12.33766114 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.13936794 </eps>
  <enl>          1.99162178 </enl>
  <ecoul>       -7.18071296 </ecoul>
  <exc>         -4.08144298 </exc>
  <esr>          1.41485664 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224097 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224097 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01188146 -0.00007115 -0.00000806 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00010268 -0.00000945 0.00000005 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13446302 1.45920580 -0.00006523 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00005097 -0.00000402 -0.00000000 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13449117 -1.45921454 -0.00003762 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00003252 -0.00002081 0.00000000 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224097 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 1.32403118
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04219550 </eigenvalue_sum>
  <etotal_int>     -17.07224052 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04213717 </eigenvalue_sum>
  Anderson extrapolation: theta=1.38172023 (1.38172023)
  <etotal_int>     -17.07224079 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04205938 </eigenvalue_sum>
  Anderson extrapolation: theta=0.05071693 (0.05071693)
  <etotal_int>     -17.07224097 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04205756 </eigenvalue_sum>
  Anderson extrapolation: theta=1.59221138 (1.59221138)
  <etotal_int>     -17.07224097 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04205487 </eigenvalue_sum>
  Anderson extrapolation: theta=0.13559309 (0.13559309)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04205429 </eigenvalue_sum>
  Anderson extrapolation: theta=1.86205804 (1.86205804)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04205245 </eigenvalue_sum>
  Anderson extrapolation: theta=0.19308027 (0.19308027)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04205145 </eigenvalue_sum>
  Anderson extrapolation: theta=1.36156871 (1.36156871)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04204973 </eigenvalue_sum>
  Anderson extrapolation: theta=0.23825303 (0.23825303)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04204909 </eigenvalue_sum>
  Anderson extrapolation: theta=1.71212375 (1.71212375)
  <etotal_int>     -17.07224098 </etotal_int>
  <timing name="iteration" min="    1.342" max="    1.343"/>
</iteration>
<iteration count="13">
  total_electronic_charge: 8.00000000
  <ekin>        12.33791367 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.13984193 </eps>
  <enl>          1.99157382 </enl>
  <ecoul>       -7.18039189 </ecoul>
  <exc>         -4.08149465 </exc>
  <esr>          1.41511302 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224098 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224098 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01174913 -0.00007899 -0.00000800 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00000600 0.00001968 0.00000002 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13439722 1.45919338 -0.00006523 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00001365 0.00002984 -0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13445300 -1.45923903 -0.00003762 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00000187 -0.00004975 -0.00000000 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224098 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 1.32403118
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201133 </eigenvalue_sum>
  <etotal_int>     -17.07224095 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201887 </eigenvalue_sum>
  Anderson extrapolation: theta=1.40134497 (1.40134497)
  <etotal_int>     -17.07224097 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203053 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04796194 (0.04796194)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203197 </eigenvalue_sum>
  Anderson extrapolation: theta=1.61057919 (1.61057919)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203465 </eigenvalue_sum>
  Anderson extrapolation: theta=0.14352619 (0.14352619)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203526 </eigenvalue_sum>
  Anderson extrapolation: theta=1.99210251 (1.99210251)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203641 </eigenvalue_sum>
  Anderson extrapolation: theta=0.23886335 (0.23886335)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203658 </eigenvalue_sum>
  Anderson extrapolation: theta=1.48773209 (1.48773209)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203671 </eigenvalue_sum>
  Anderson extrapolation: theta=0.29791660 (0.29791660)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203666 </eigenvalue_sum>
  Anderson extrapolation: theta=1.52915326 (1.52915326)
  <etotal_int>     -17.07224098 </etotal_int>
  <timing name="iteration" min="    1.346" max="    1.346"/>
</iteration>
<iteration count="14">
  total_electronic_charge: 8.00000000
  <ekin>        12.33788362 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.13976313 </eps>
  <enl>          1.99156909 </enl>
  <ecoul>       -7.18044475 </ecoul>
  <exc>         -4.08148581 </exc>
  <esr>          1.41506794 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224098 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224098 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01172806 -0.00005465 -0.00000796 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00000255 -0.00001212 0.00000003 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13436473 1.45923017 -0.00006524 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00000347 0.00003285 -0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13444711 -1.45931027 -0.00003762 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00001194 -0.00002212 0.00000000 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224098 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 2.78046547
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04199620 </eigenvalue_sum>
  <etotal_int>     -17.07224095 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200445 </eigenvalue_sum>
  Anderson extrapolation: theta=1.40101188 (1.40101188)
  <etotal_int>     -17.07224097 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201719 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04810025 (0.04810025)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201873 </eigenvalue_sum>
  Anderson extrapolation: theta=1.61336921 (1.61336921)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04202162 </eigenvalue_sum>
  Anderson extrapolation: theta=0.14329559 (0.14329559)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04202227 </eigenvalue_sum>
  Anderson extrapolation: theta=1.97378614 (1.97378614)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04202347 </eigenvalue_sum>
  Anderson extrapolation: theta=0.23537194 (0.23537194)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04202365 </eigenvalue_sum>
  Anderson extrapolation: theta=1.48751143 (1.48751143)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04202378 </eigenvalue_sum>
  Anderson extrapolation: theta=0.29979338 (0.29979338)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04202372 </eigenvalue_sum>
  Anderson extrapolation: theta=1.55746894 (1.55746894)
  <etotal_int>     -17.07224098 </etotal_int>
  <timing name="iteration" min="    1.334" max="    1.335"/>
</iteration>
<iteration count="15">
  total_electronic_charge: 8.00000000
  <ekin>        12.33785161 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.13967760 </eps>
  <enl>          1.99156405 </enl>
  <ecoul>       -7.18050268 </ecoul>
  <exc>         -4.08147636 </exc>
  <esr>          1.41501836 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224098 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224098 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01170490 -0.00002788 -0.00000791 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00000565 -0.00004639 0.00000002 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13432899 1.45927064 -0.00006525 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00000821 0.00003660 -0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13444063 -1.45938863 -0.00003762 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00002692 0.00000808 0.00000000 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224098 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 2.78046547
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04191669 </eigenvalue_sum>
  <etotal_int>     -17.07224073 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04193782 </eigenvalue_sum>
  Anderson extrapolation: theta=1.42563894 (1.42563894)
  <etotal_int>     -17.07224088 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04197110 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04919859 (0.04919859)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04197531 </eigenvalue_sum>
  Anderson extrapolation: theta=1.63900686 (1.63900686)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04198325 </eigenvalue_sum>
  Anderson extrapolation: theta=0.14218160 (0.14218160)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04198498 </eigenvalue_sum>
  Anderson extrapolation: theta=1.88735528 (1.88735528)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04198803 </eigenvalue_sum>
  Anderson extrapolation: theta=0.20870215 (0.20870215)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04198838 </eigenvalue_sum>
  Anderson extrapolation: theta=1.45974616 (1.45974616)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04198860 </eigenvalue_sum>
  Anderson extrapolation: theta=0.27629113 (0.27629113)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04198845 </eigenvalue_sum>
  Anderson extrapolation: theta=1.64519036 (1.64519036)
  <etotal_int>     -17.07224099 </etotal_int>
  <timing name="iteration" min="    1.347" max="    1.348"/>
</iteration>
<iteration count="16">
  total_electronic_charge: 8.00000000
  <ekin>        12.33777340 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.13945578 </eps>
  <enl>          1.99154595 </enl>
  <ecoul>       -7.18065279 </ecoul>
  <exc>         -4.08145177 </exc>
  <esr>          1.41488869 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224099 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224099 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01163585 -0.00009521 -0.00000772 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00000711 0.00001816 0.00000001 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13426953 1.45946559 -0.00006529 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00001741 -0.00002982 -0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13435086 -1.45954663 -0.00003762 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00000630 0.00001580 -0.00000000 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224099 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 1.67641959
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203054 </eigenvalue_sum>
  <etotal_int>     -17.07224095 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04202216 </eigenvalue_sum>
  Anderson extrapolation: theta=1.42382219 (1.42382219)
  <etotal_int>     -17.07224097 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200889 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04979372 (0.04979372)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200719 </eigenvalue_sum>
  Anderson extrapolation: theta=1.66197628 (1.66197628)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200397 </eigenvalue_sum>
  Anderson extrapolation: theta=0.14354224 (0.14354224)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200329 </eigenvalue_sum>
  Anderson extrapolation: theta=1.84112312 (1.84112312)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200212 </eigenvalue_sum>
  Anderson extrapolation: theta=0.19512472 (0.19512472)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200201 </eigenvalue_sum>
  Anderson extrapolation: theta=1.41044152 (1.41044152)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200197 </eigenvalue_sum>
  Anderson extrapolation: theta=0.24835641 (0.24835641)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200205 </eigenvalue_sum>
  Anderson extrapolation: theta=1.63860075 (1.63860075)
  <etotal_int>     -17.07224099 </etotal_int>
  <timing name="iteration" min="    1.360" max="    1.360"/>
</iteration>
<iteration count="17">
  total_electronic_charge: 8.00000000
  <ekin>        12.33780299 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.13954393 </eps>
  <enl>          1.99155468 </enl>
  <ecoul>       -7.18059321 </ecoul>
  <exc>         -4.08146152 </exc>
  <esr>          1.41494018 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224099 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224099 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01166326 -0.00006847 -0.00000779 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00001144 -0.00001112 0.00000003 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13429314 1.45938818 -0.00006527 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00000686 -0.00000327 -0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13438650 -1.45948389 -0.00003762 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00001452 0.00001301 -0.00000000 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224099 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 1.67641959
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04206502 </eigenvalue_sum>
  <etotal_int>     -17.07224097 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04204747 </eigenvalue_sum>
  Anderson extrapolation: theta=1.34736912 (1.34736912)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04202358 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04729261 (0.04729261)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04202223 </eigenvalue_sum>
  Anderson extrapolation: theta=1.54714452 (1.54714452)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201994 </eigenvalue_sum>
  Anderson extrapolation: theta=0.13763158 (0.13763158)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201943 </eigenvalue_sum>
  Anderson extrapolation: theta=1.97861719 (1.97861719)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201830 </eigenvalue_sum>
  Anderson extrapolation: theta=0.24412761 (0.24412761)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201795 </eigenvalue_sum>
  Anderson extrapolation: theta=1.41926166 (1.41926166)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201745 </eigenvalue_sum>
  Anderson extrapolation: theta=0.28524946 (0.28524946)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201733 </eigenvalue_sum>
  Anderson extrapolation: theta=1.55717433 (1.55717433)
  <etotal_int>     -17.07224099 </etotal_int>
  <timing name="iteration" min="    1.337" max="    1.338"/>
</iteration>
<iteration count="18">
  total_electronic_charge: 8.00000000
  <ekin>        12.33787790 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.13969646 </eps>
  <enl>          1.99154543 </enl>
  <ecoul>       -7.18048975 </ecoul>
  <exc>         -4.08147811 </exc>
  <esr>          1.41502397 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224099 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224099 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01164607 -0.00008519 -0.00000774 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00001084 0.00000860 0.00000003 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13428335 1.45937711 -0.00006528 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00000387 0.00000043 -0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13436474 -1.45945757 -0.00003762 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00000234 -0.00000829 -0.00000000 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224099 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 1.67641959
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04198832 </eigenvalue_sum>
  <etotal_int>     -17.07224097 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04199705 </eigenvalue_sum>
  Anderson extrapolation: theta=1.36435510 (1.36435510)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200867 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04879662 (0.04879662)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200902 </eigenvalue_sum>
  Anderson extrapolation: theta=1.54615088 (1.54615088)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200955 </eigenvalue_sum>
  Anderson extrapolation: theta=0.12823436 (0.12823436)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200966 </eigenvalue_sum>
  Anderson extrapolation: theta=1.88601157 (1.88601157)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200996 </eigenvalue_sum>
  Anderson extrapolation: theta=0.20555786 (0.20555786)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201010 </eigenvalue_sum>
  Anderson extrapolation: theta=1.35822284 (1.35822284)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201035 </eigenvalue_sum>
  Anderson extrapolation: theta=0.23697371 (0.23697371)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201044 </eigenvalue_sum>
  Anderson extrapolation: theta=1.60158067 (1.60158067)
  <etotal_int>     -17.07224099 </etotal_int>
  <timing name="iteration" min="    1.335" max="    1.335"/>
</iteration>
<iteration count="19">
  total_electronic_charge: 8.00000000
  <ekin>        12.33784284 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.13962573 </eps>
  <enl>          1.99154984 </enl>
  <ecoul>       -7.18053757 </ecoul>
  <exc>         -4.08147036 </exc>
  <esr>          1.41498539 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224099 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224099 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01166424 -0.00007076 -0.00000770 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00000011 -0.00000776 0.00000003 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13427686 1.45937784 -0.00006529 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00000266 0.00000238 -0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13436866 -1.45947146 -0.00003762 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00000841 0.00000495 -0.00000000 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224099 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 1.67641959
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04199452 </eigenvalue_sum>
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04199981 </eigenvalue_sum>
  Anderson extrapolation: theta=1.38162360 (1.38162360)
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200659 </eigenvalue_sum>
  Anderson extrapolation: theta=0.05195157 (0.05195157)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200654 </eigenvalue_sum>
  Anderson extrapolation: theta=1.55846085 (1.55846085)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200633 </eigenvalue_sum>
  Anderson extrapolation: theta=0.12968398 (0.12968398)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200626 </eigenvalue_sum>
  Anderson extrapolation: theta=1.82609172 (1.82609172)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200623 </eigenvalue_sum>
  Anderson extrapolation: theta=0.19621101 (0.19621101)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200630 </eigenvalue_sum>
  Anderson extrapolation: theta=1.35535857 (1.35535857)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200645 </eigenvalue_sum>
  Anderson extrapolation: theta=0.23244844 (0.23244844)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04200652 </eigenvalue_sum>
  Anderson extrapolation: theta=1.61841249 (1.61841249)
  <etotal_int>     -17.07224099 </etotal_int>
  <timing name="iteration" min="    1.351" max="    1.352"/>
</iteration>
<iteration count="20">
  total_electronic_charge: 8.00000000
  <ekin>        12.33782411 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.13958710 </eps>
  <enl>          1.99155204 </enl>
  <ecoul>       -7.18056384 </ecoul>
  <exc>         -4.08146618 </exc>
  <esr>          1.41496404 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07224099 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07224099 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> -0.01168254 -0.00006911 -0.00000761 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00000521 -0.00000874 0.00000002 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.13426582 1.45938257 -0.00006531 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00000458 -0.00000013 -0.00000001 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.13435854 -1.45947729 -0.00003762 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00001142 0.00000886 -0.00000000 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <econst> -17.07224099 </econst>
  <ekin_ion> 0.00000000 </ekin_ion>
  <temp_ion> 0.00000000 </temp_ion>
  CGIonicStepper: alpha = 1.67641959
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04203063 </eigenvalue_sum>
  <etotal_int>     -17.07224098 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04202445 </eigenvalue_sum>
  Anderson extrapolation: theta=1.36822848 (1.36822848)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201558 </eigenvalue_sum>
  Anderson extrapolation: theta=0.04933970 (0.04933970)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201480 </eigenvalue_sum>
  Anderson extrapolation: theta=1.61023150 (1.61023150)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201336 </eigenvalue_sum>
  Anderson extrapolation: theta=0.14728732 (0.14728732)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201303 </eigenvalue_sum>
  Anderson extrapolation: theta=1.96144146 (1.96144146)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201238 </eigenvalue_sum>
  Anderson extrapolation: theta=0.24519569 (0.24519569)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201224 </eigenvalue_sum>
  Anderson extrapolation: theta=1.46830250 (1.46830250)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201210 </eigenvalue_sum>
  Anderson extrapolation: theta=0.30947513 (0.30947513)
  <etotal_int>     -17.07224099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.04201209 </eigenvalue_sum>
  Anderson extrapolation: theta=1.55903062 (1.55903062)
  <etotal_int>     -17.07224099 </etotal_int>
  <timing name="iteration" min="    1.375" max="    1.376"/>
</iteration>
  total_electronic_charge: 8.00000000
<timing name="         charge" min="    8.956" max="    9.117"/>
<timing name="         energy" min="    8.291" max="    8.649"/>
<timing name="    ortho_align" min="    0.155" max="    0.223"/>
<timing name="      psda_prec" min="    0.055" max="    0.057"/>
<timing name="  psda_residual" min="    0.063" max="    0.107"/>
<timing name=" psda_update_wf" min="    0.063" max="    0.133"/>
<timing name="    update_vhxc" min="    9.397" max="    9.741"/>
<timing name="      wf_update" min="    0.532" max="    0.574"/>
<timing name="           ekin" min="    0.206" max="    0.571"/>
<timing name="            exc" min="    4.311" max="    4.464"/>
<timing name="           hpsi" min="    7.023" max="    7.172"/>
<timing name="       nonlocal" min="    0.829" max="    0.976"/>
<timing name=" charge_compute" min="    4.455" max="    4.888"/>
<timing name="charge_integral" min="    0.336" max="    0.800"/>
<timing name="  charge_rowsum" min="    0.220" max="    0.336"/>
<timing name="     charge_vft" min="    3.478" max="    3.638"/>
[qbox] <cmd>distance O H1</cmd>
 distance O-H1: 1.856 (a.u.) / 0.982 (Ang)
[qbox] <cmd>distance O H2</cmd>
 distance O-H2: 1.856 (a.u.) / 0.982 (Ang)
[qbox] <cmd>angle H1 O H2</cmd>
 angle H1-O-H2: 103.720 (deg)
[qbox] <cmd>save test.xml</cmd>
 SampleWriter: write time: 0.030 s
 SampleWriter: file size: 3959423
 SampleWriter: aggregate write rate: 127.56 MB/s
[qbox]  End of command stream 
<real_time> 28.06 </real_time>
<end_time> 2016-04-06T12:25:00Z </end_time>
</fpmd:simulation>
