<?xml version="1.0" encoding="UTF-8"?>
<fpmd:simulation xmlns:fpmd="http://www.quantum-simulation.org/ns/fpmd/fpmd-1.0">

                   ============================
                   I qbox 1.63.2              I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I http://qboxcode.org      I
                   ============================


<release> 1.63.2 dell </release>
<sysname> Linux </sysname>
<nodename> theobook68 </nodename>
<start_time> 2016-04-29T09:48:23Z </start_time>
<mpi_processes count="4">
<process id="0"> theobook68 </process>
<process id="1"> theobook68 </process>
<process id="2"> theobook68 </process>
<process id="3"> theobook68 </process>
</mpi_processes>
[qbox] <cmd># Oxygen dimer</cmd>
[qbox] <cmd># triplet state</cmd>
[qbox] <cmd>set cell 11 0 0  0 11 0  0 0 11</cmd>
<unit_cell 
    a="11.00000000  0.00000000   0.00000000  "
    b="0.00000000   11.00000000  0.00000000  "
    c="0.00000000   0.00000000   11.00000000 " />
[qbox] <cmd>species oxygen O_HSCV_PBE-1.0.xml</cmd>
  SpeciesCmd: defining species oxygen as O_HSCV_PBE-1.0.xml

 species oxygen:
<species name="oxygen">
 <description>
 PSGen-1.6.0 pseudopotential: HSCV O xc=PBE
 Generated by PSGen-1.6.0 on 2009-02-15T02:25:11Z
 psgen arguments:
 -element O -xc PBE -smooth_v -bound l=0:rc=0.8 -bound l=1:rc=0.8
 </description>
 <symbol>O</symbol>
 <atomic_number>8</atomic_number>
 <mass>15.99940000</mass>
 <norm_conserving_pseudopotential>
 <valence_charge>6</valence_charge>
 <lmax>1</lmax>
 <llocal>1</llocal>
 <nquad>0</nquad>
 <rquad>0.00000000</rquad>
 <mesh_spacing>0.01000000</mesh_spacing>
 </norm_conserving_pseudopotential>
</species>
 Kleinman-Bylander potential
 rcps_ =   1.50000000
[qbox] <cmd>atom O1 oxygen  1.16  0  0</cmd>
[qbox] <cmd>atom O2 oxygen -1.16  0  0</cmd>
[qbox] <cmd>set nspin 2</cmd>
[qbox] <cmd>set delta_spin 1</cmd>
[qbox] <cmd>set nempty 4</cmd>
[qbox] <cmd>set ecut 70</cmd>
[qbox] <cmd>set wf_dyn JD</cmd>
[qbox] <cmd>randomize_wf</cmd>
[qbox] <cmd>run 0 40 5 </cmd>
  EnergyFunctional: np0v,np1v,np2v: 64 64 64
  EnergyFunctional: vft->np012(): 262144
<wavefunction ecut="35.00000000" nspin="2" nel="12" nempty="4">
<cell a="11.000000 0.000000 0.000000"
      b="0.000000 11.000000 0.000000"
      c="0.000000 0.000000 11.000000"/>
 reciprocal lattice vectors
 0.571199 0.000000 0.000000
 0.000000 0.571199 0.000000
 0.000000 0.000000 0.571199
<refcell a="0.000000 0.000000 0.000000"
         b="0.000000 0.000000 0.000000"
         c="0.000000 0.000000 0.000000"/>
<grid nx="32" ny="32" nz="32"/>
 kpoint: 0.000000 0.000000 0.000000 weight: 1.000000
<slater_determinant kpoint="0.000000 0.000000 0.000000" size="11">
 sdcontext: 4x1
 basis size: 6603
 c dimensions: 6660x11   (1665x11 blocks)
 <density_matrix form="diagonal" size="11">
 </density_matrix>
</slater_determinant>
 kpoint: 0.000000 0.000000 0.000000 weight: 1.000000
<slater_determinant kpoint="0.000000 0.000000 0.000000" size="9">
 sdcontext: 4x1
 basis size: 6603
 c dimensions: 6660x9   (1665x9 blocks)
 <density_matrix form="diagonal" size="9">
 </density_matrix>
</slater_determinant>
</wavefunction>
<iteration count="1">
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
  <eigenvalue_sum>  205.99814332 </eigenvalue_sum>
  <eigenvalue_sum>  32.17760153 </eigenvalue_sum>
  <eigenvalue_sum>  7.56823070 </eigenvalue_sum>
  <eigenvalue_sum>  0.53882139 </eigenvalue_sum>
  <eigenvalue_sum>  -2.98911685 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -88.42131   -13.05280    -8.13075    -3.51017    -2.54285
    -1.47091     0.91961     9.15516    10.56718    11.49228
    15.38262
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -87.57094    -9.57076    -2.91210    -2.01555    -1.05502
     1.40815     6.26086    11.02477    12.35999
  </eigenvalues>
</eigenset>
  <etotal_int>     -11.55577738 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
  <eigenvalue_sum>  -5.53051619 </eigenvalue_sum>
  <eigenvalue_sum>  -7.26003765 </eigenvalue_sum>
  <eigenvalue_sum>  -8.87607091 </eigenvalue_sum>
  <eigenvalue_sum>  -10.65401663 </eigenvalue_sum>
  <eigenvalue_sum>  -12.63701856 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
  -114.18866   -41.04255   -31.35088   -29.21028   -13.14233
    -6.82878    -5.83968     0.36027     6.79431     8.07794
     9.12512
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
  -113.76208   -35.48907   -25.85859   -14.24840    -7.57965
    -5.80144    -1.33870     4.02358     8.07744
  </eigenvalues>
</eigenset>
  <etotal_int>     -19.00092832 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.37184107 
  <eigenvalue_sum>  -13.74202243 </eigenvalue_sum>
  <eigenvalue_sum>  -16.12108832 </eigenvalue_sum>
  <eigenvalue_sum>  -19.06524849 </eigenvalue_sum>
  <eigenvalue_sum>  -22.15181006 </eigenvalue_sum>
  <eigenvalue_sum>  -25.95030748 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
  -113.10513   -79.39724   -69.66394   -69.07671   -54.08820
   -28.59120   -15.39668    -9.24233    -1.95281    -1.49998
     5.31931
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
  -111.76529   -73.49886   -61.58404   -47.29120   -33.58273
   -22.73725   -12.62378    -6.45429     0.30077
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.27360019 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.83132153 -0.02581769 
  <eigenvalue_sum>  -29.21863419 </eigenvalue_sum>
  <eigenvalue_sum>  -33.70953551 </eigenvalue_sum>
  <eigenvalue_sum>  -37.59976490 </eigenvalue_sum>
  <eigenvalue_sum>  -43.23378136 </eigenvalue_sum>
  <eigenvalue_sum>  -47.16577256 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
  -118.04361   -99.23434   -94.68546   -92.88486   -89.95505
   -82.54624   -79.84913   -43.77022   -27.16693   -18.92982
    -9.53707
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
  -117.04789   -95.11513   -90.63567   -88.11069   -87.05611
   -79.64191   -77.69216   -35.72451   -17.45181
  </eigenvalues>
</eigenset>
  <etotal_int>     -45.32500657 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.76352128 0.56356611 0.01988104 
  <eigenvalue_sum>  -53.55726248 </eigenvalue_sum>
  <eigenvalue_sum>  -55.95046086 </eigenvalue_sum>
  <eigenvalue_sum>  -58.02664704 </eigenvalue_sum>
  <eigenvalue_sum>  -58.78746016 </eigenvalue_sum>
  <eigenvalue_sum>  -59.11224382 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
  -122.77603  -102.33757  -101.46682   -98.69598   -91.51851
   -81.90407   -80.26412   -76.66038   -33.27594   -30.44446
   -25.37939
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
  -118.55809   -98.65192   -93.69672   -92.15114   -90.72022
   -83.05393   -82.81938   -76.14067   -32.96883
  </eigenvalues>
</eigenset>
  <etotal_int>     -46.57933474 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.21664306 0.71940464 0.59471634 
  <eigenvalue_sum>  -58.87161085 </eigenvalue_sum>
  <eigenvalue_sum>  -58.98825816 </eigenvalue_sum>
  <eigenvalue_sum>  -59.06847724 </eigenvalue_sum>
  <eigenvalue_sum>  -59.12863214 </eigenvalue_sum>
  <eigenvalue_sum>  -59.17725931 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
  -121.26355  -101.50189   -99.49845   -98.33142   -91.29484
   -81.82666   -81.05284   -78.00087   -33.56351   -30.23189
   -28.08546
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
  -117.73185   -98.63740   -92.43948   -92.28147   -90.65293
   -82.57818   -82.39584   -77.11975   -32.89277
  </eigenvalues>
</eigenset>
  <etotal_int>     -46.40101490 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.01471772 0.06794305 0.92873273 
  <eigenvalue_sum>  -47.09505443 </eigenvalue_sum>
  <eigenvalue_sum>  -47.20663548 </eigenvalue_sum>
  <eigenvalue_sum>  -47.24239490 </eigenvalue_sum>
  <eigenvalue_sum>  -47.26344700 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
  -100.22793   -81.94889   -77.26929   -77.05451   -74.65341
   -67.28757   -67.01498   -61.28681   -22.92305   -18.64238
   -18.19994
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -99.12763   -80.80602   -75.46139   -75.18438   -73.68176
   -66.86497   -66.52993   -60.13128   -22.23440
  </eigenvalues>
</eigenset>
  <etotal_int>     -40.89403911 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.59396975 -0.57091064 -0.37480442 
  <eigenvalue_sum>  -15.33277942 </eigenvalue_sum>
  <eigenvalue_sum>  -16.80847976 </eigenvalue_sum>
  <eigenvalue_sum>  -17.07439294 </eigenvalue_sum>
  <eigenvalue_sum>  -17.19557485 </eigenvalue_sum>
  <eigenvalue_sum>  -17.28452003 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -53.39190   -38.96775   -33.39851   -33.31984   -29.97623
   -21.71147   -21.61717   -12.86024    -1.03826     3.69547
     4.35591
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -52.05564   -37.47791   -31.22522   -31.04721   -28.97247
   -20.42437   -20.34631   -11.69591    -0.82226
  </eigenvalues>
</eigenset>
  <etotal_int>     -32.83693022 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.74025274 -0.28389848 -0.19492850 
  <eigenvalue_sum>  -12.86787360 </eigenvalue_sum>
  <eigenvalue_sum>  -13.04120430 </eigenvalue_sum>
  <eigenvalue_sum>  -13.13627451 </eigenvalue_sum>
  <eigenvalue_sum>  -13.22500985 </eigenvalue_sum>
  <eigenvalue_sum>  -13.28671510 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -45.39546   -32.09271   -24.99873   -24.83161   -24.73296
   -17.82030   -17.78605    -6.96385     0.90247     5.73669
     6.38123
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -44.21411   -30.53014   -23.77131   -23.41807   -23.38874
   -16.02492   -15.89508    -5.51457     1.19627
  </eigenvalues>
</eigenset>
  <etotal_int>     -32.14254996 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.08837618 -0.38237146 0.22327472 
  <eigenvalue_sum>  -9.49344912 </eigenvalue_sum>
  <eigenvalue_sum>  -9.55805188 </eigenvalue_sum>
  <eigenvalue_sum>  -9.61653769 </eigenvalue_sum>
  <eigenvalue_sum>  -9.67072190 </eigenvalue_sum>
  <eigenvalue_sum>  -9.72669090 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -39.09589   -26.72143   -19.45109   -19.38952   -19.28532
   -12.52025   -12.49564    -1.50348     3.06744     7.49260
     8.15069
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -37.81676   -25.06035   -18.45012   -17.74413   -17.72549
   -10.51008   -10.47852     0.03251     3.36825
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.78241049 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.96650807 -0.09595877 0.02347292 
  <eigenvalue_sum>  -5.91571426 </eigenvalue_sum>
  <eigenvalue_sum>  -6.05166973 </eigenvalue_sum>
  <eigenvalue_sum>  -6.13723855 </eigenvalue_sum>
  <eigenvalue_sum>  -6.20289794 </eigenvalue_sum>
  <eigenvalue_sum>  -6.25914982 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -32.93363   -21.31692   -14.10191   -13.84915   -13.84075
    -7.24673    -7.21869     3.56754     5.17029     8.48486
     9.08546
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -31.53307   -19.55205   -13.03934   -12.10958   -12.08540
    -5.06425    -4.98226     5.27221     5.49636
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.62934391 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.58888610 0.20086566 0.02229004 
  <eigenvalue_sum>  -6.20662396 </eigenvalue_sum>
  <eigenvalue_sum>  -6.25785142 </eigenvalue_sum>
  <eigenvalue_sum>  -6.30343959 </eigenvalue_sum>
  <eigenvalue_sum>  -6.33907482 </eigenvalue_sum>
  <eigenvalue_sum>  -6.37392932 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -32.93692   -21.06992   -13.96400   -13.70865   -13.70163
    -7.11738    -7.09708     3.35953     4.30772     7.58749
     8.16860
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -31.53643   -19.27970   -12.85027   -11.94138   -11.93054
    -4.96596    -4.96174     4.46900     4.92250
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.63672530 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.89889283 0.30736577 -0.15577325 
  <eigenvalue_sum>  -6.31551207 </eigenvalue_sum>
  <eigenvalue_sum>  -6.34576202 </eigenvalue_sum>
  <eigenvalue_sum>  -6.37046908 </eigenvalue_sum>
  <eigenvalue_sum>  -6.39444347 </eigenvalue_sum>
  <eigenvalue_sum>  -6.41613086 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -32.83619   -20.85624   -13.81463   -13.54303   -13.53748
    -6.95654    -6.94917     3.27774     3.47949     6.86878
     7.60900
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -31.44575   -19.05699   -12.66327   -11.77230   -11.76906
    -4.81150    -4.80727     3.65132     4.71108
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.65131105 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.12364861 -0.39989928 0.09394342 
  <eigenvalue_sum>  -6.72433204 </eigenvalue_sum>
  <eigenvalue_sum>  -6.74570453 </eigenvalue_sum>
  <eigenvalue_sum>  -6.76725687 </eigenvalue_sum>
  <eigenvalue_sum>  -6.78738983 </eigenvalue_sum>
  <eigenvalue_sum>  -6.80983524 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.27261   -21.19790   -14.17959   -13.91119   -13.90253
    -7.31600    -7.30919     2.29990     2.83290     5.92371
     6.79534
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -31.89879   -19.40425   -13.01753   -12.15192   -12.14557
    -5.20530    -5.20132     2.23092     4.15288
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.65825680 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.02857582 -0.41630623 0.14358808 
  <eigenvalue_sum>  -6.90326107 </eigenvalue_sum>
  <eigenvalue_sum>  -6.94071140 </eigenvalue_sum>
  <eigenvalue_sum>  -6.96939035 </eigenvalue_sum>
  <eigenvalue_sum>  -6.98984921 </eigenvalue_sum>
  <eigenvalue_sum>  -7.00670438 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.33421   -21.25749   -14.24707   -13.97284   -13.96592
    -7.37865    -7.37616     1.34582     2.55775     5.21440
     6.18234
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -31.96754   -19.46747   -13.08553   -12.21621   -12.21261
    -5.27482    -5.27150     0.59360     3.98475
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66221671 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.28663204 -0.01123945 0.01188165 
  <eigenvalue_sum>  -7.08014743 </eigenvalue_sum>
  <eigenvalue_sum>  -7.09470072 </eigenvalue_sum>
  <eigenvalue_sum>  -7.10971503 </eigenvalue_sum>
  <eigenvalue_sum>  -7.12276207 </eigenvalue_sum>
  <eigenvalue_sum>  -7.13382593 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.39632   -21.31853   -14.30833   -14.02927   -14.02658
    -7.44441    -7.44237     0.68482     2.40657     4.67450
     5.79026
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.03300   -19.53189   -13.14984   -12.27669   -12.27585
    -5.33944    -5.33876     0.26386     3.67850
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66359633 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.79249451 0.35135677 -0.09915252 
  <eigenvalue_sum>  -7.21336462 </eigenvalue_sum>
  <eigenvalue_sum>  -7.22409922 </eigenvalue_sum>
  <eigenvalue_sum>  -7.23396560 </eigenvalue_sum>
  <eigenvalue_sum>  -7.24447306 </eigenvalue_sum>
  <eigenvalue_sum>  -7.25372050 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.50501   -21.40746   -14.39698   -14.11970   -14.11888
    -7.53697    -7.53646     0.20229     2.29122     4.20053
     5.45889
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.14225   -19.62008   -13.23795   -12.36632   -12.36515
    -5.43386    -5.43169    -0.07868     3.52047
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66395415 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.28869852 -0.22262116 0.04132364 
  <eigenvalue_sum>  -7.31151731 </eigenvalue_sum>
  <eigenvalue_sum>  -7.31943746 </eigenvalue_sum>
  <eigenvalue_sum>  -7.32795624 </eigenvalue_sum>
  <eigenvalue_sum>  -7.33591539 </eigenvalue_sum>
  <eigenvalue_sum>  -7.34590988 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.57068   -21.46453   -14.45381   -14.17681   -14.17637
    -7.59583    -7.59506    -0.14123     2.19663     3.62444
     5.12780
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.20820   -19.67734   -13.29478   -12.42277   -12.42155
    -5.49283    -5.49143    -0.34434     3.42579
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66416438 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.38593960 0.28092904 -0.03716271 
  <eigenvalue_sum>  -7.35125509 </eigenvalue_sum>
  <eigenvalue_sum>  -7.37391463 </eigenvalue_sum>
  <eigenvalue_sum>  -7.39021786 </eigenvalue_sum>
  <eigenvalue_sum>  -7.41139053 </eigenvalue_sum>
  <eigenvalue_sum>  -7.41856644 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.55710   -21.45473   -14.44423   -14.16671   -14.16654
    -7.58532    -7.58490    -0.42348     2.06390     2.50035
     4.87350
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.19511   -19.66824   -13.28586   -12.41357   -12.41244
    -5.48322    -5.48190    -0.51701     3.40399
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66420102 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.55221524 -0.78448490 0.25343977 
  <eigenvalue_sum>  -7.43901241 </eigenvalue_sum>
  <eigenvalue_sum>  -7.44419563 </eigenvalue_sum>
  <eigenvalue_sum>  -7.44856440 </eigenvalue_sum>
  <eigenvalue_sum>  -7.45245587 </eigenvalue_sum>
  <eigenvalue_sum>  -7.45630719 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.56858   -21.46527   -14.45460   -14.17750   -14.17741
    -7.59605    -7.59588    -0.66831     2.04043     2.36203
     4.69066
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.20758   -19.67964   -13.29715   -12.42488   -12.42414
    -5.49430    -5.49340    -0.72360     3.36291
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66423867 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.76117991 0.60368430 -0.03665286 
  <eigenvalue_sum>  -7.46943810 </eigenvalue_sum>
  <eigenvalue_sum>  -7.47374819 </eigenvalue_sum>
  <eigenvalue_sum>  -7.47735463 </eigenvalue_sum>
  <eigenvalue_sum>  -7.48167636 </eigenvalue_sum>
  <eigenvalue_sum>  -7.48578110 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.58389   -21.47767   -14.46705   -14.19020   -14.19017
    -7.60884    -7.60871    -0.95365     2.01731     2.32690
     4.30801
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.22346   -19.69244   -13.30959   -12.43764   -12.43747
    -5.50713    -5.50695    -0.84054     3.32160
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66424649 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.33238644 -0.80090286 0.34571366 
  <eigenvalue_sum>  -7.50998708 </eigenvalue_sum>
  <eigenvalue_sum>  -7.52214476 </eigenvalue_sum>
  <eigenvalue_sum>  -7.52602120 </eigenvalue_sum>
  <eigenvalue_sum>  -7.52913306 </eigenvalue_sum>
  <eigenvalue_sum>  -7.53233067 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.59768   -21.48912   -14.47848   -14.20210   -14.20203
    -7.62057    -7.62045    -1.16187     1.97323     2.27226
     3.96380
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.23835   -19.70481   -13.32161   -12.45030   -12.45014
    -5.51971    -5.51951    -0.95936     3.27521
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66425168 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.86296752 0.43353935 -0.16885520 
  <eigenvalue_sum>  -7.54155306 </eigenvalue_sum>
  <eigenvalue_sum>  -7.55078978 </eigenvalue_sum>
  <eigenvalue_sum>  -7.55788624 </eigenvalue_sum>
  <eigenvalue_sum>  -7.56178063 </eigenvalue_sum>
  <eigenvalue_sum>  -7.57316445 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60344   -21.49391   -14.48325   -14.20732   -14.20723
    -7.62548    -7.62538    -1.25606     1.78353     2.21123
     3.69660
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24502   -19.71040   -13.32707   -12.45630   -12.45602
    -5.52543    -5.52514    -1.16524     2.82901
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66425649 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.16872668 -0.65565428 0.39896801 
  <eigenvalue_sum>  -7.58450915 </eigenvalue_sum>
  <eigenvalue_sum>  -7.58893164 </eigenvalue_sum>
  <eigenvalue_sum>  -7.59164969 </eigenvalue_sum>
  <eigenvalue_sum>  -7.59415440 </eigenvalue_sum>
  <eigenvalue_sum>  -7.59668499 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60163   -21.49250   -14.48187   -14.20590   -14.20585
    -7.62394    -7.62390    -1.33625     1.77946     2.20095
     3.52998
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24334   -19.70907   -13.32579   -12.45500   -12.45485
    -5.52401    -5.52385    -1.27453     2.79185
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66425813 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.24672454 0.15466127 -0.21771821 
  <eigenvalue_sum>  -7.60195382 </eigenvalue_sum>
  <eigenvalue_sum>  -7.60419449 </eigenvalue_sum>
  <eigenvalue_sum>  -7.60622117 </eigenvalue_sum>
  <eigenvalue_sum>  -7.60834495 </eigenvalue_sum>
  <eigenvalue_sum>  -7.61028781 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60485   -21.49512   -14.48451   -14.20865   -14.20863
    -7.62660    -7.62659    -1.40642     1.77179     2.18339
     3.39560
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24686   -19.71194   -13.32857   -12.45799   -12.45790
    -5.52691    -5.52682    -1.36082     2.77008
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66425926 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.61528434 -0.54492185 0.27975600 
  <eigenvalue_sum>  -7.61371425 </eigenvalue_sum>
  <eigenvalue_sum>  -7.61593353 </eigenvalue_sum>
  <eigenvalue_sum>  -7.62056304 </eigenvalue_sum>
  <eigenvalue_sum>  -7.62464630 </eigenvalue_sum>
  <eigenvalue_sum>  -7.62713093 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60546   -21.49555   -14.48495   -14.20912   -14.20912
    -7.62705    -7.62705    -1.48369     1.76255     2.15599
     3.14758
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24750   -19.71238   -13.32899   -12.45848   -12.45847
    -5.52738    -5.52736    -1.40875     2.74754
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426052 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.56319274 0.24390487 -0.10197364 
  <eigenvalue_sum>  -7.62929049 </eigenvalue_sum>
  <eigenvalue_sum>  -7.63301486 </eigenvalue_sum>
  <eigenvalue_sum>  -7.63588078 </eigenvalue_sum>
  <eigenvalue_sum>  -7.63760667 </eigenvalue_sum>
  <eigenvalue_sum>  -7.63899084 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60518   -21.49532   -14.48472   -14.20890   -14.20889
    -7.62682    -7.62681    -1.56501     1.75406     2.15217
     3.01824
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24719   -19.71214   -13.32874   -12.45825   -12.45822
    -5.52715    -5.52711    -1.52086     2.72631
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426096 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.21356654 -0.07959349 -0.00678090 
  <eigenvalue_sum>  -7.64215939 </eigenvalue_sum>
  <eigenvalue_sum>  -7.64423424 </eigenvalue_sum>
  <eigenvalue_sum>  -7.64521986 </eigenvalue_sum>
  <eigenvalue_sum>  -7.64610101 </eigenvalue_sum>
  <eigenvalue_sum>  -7.64705632 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60536   -21.49543   -14.48483   -14.20903   -14.20903
    -7.62695    -7.62694    -1.59271     1.75207     2.14916
     2.95843
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24736   -19.71224   -13.32884   -12.45838   -12.45836
    -5.52727    -5.52725    -1.56681     2.70363
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426100 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.55886785 0.03719560 -0.03706764 
  <eigenvalue_sum>  -7.64816502 </eigenvalue_sum>
  <eigenvalue_sum>  -7.64942790 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65054356 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65186029 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65308014 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60548   -21.49552   -14.48492   -14.20913   -14.20913
    -7.62703    -7.62703    -1.61925     1.74991     2.14656
     2.80891
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24748   -19.71233   -13.32891   -12.45848   -12.45847
    -5.52736    -5.52735    -1.57934     2.67171
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426104 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.02783616 -0.13282067 0.02161822 
  <eigenvalue_sum>  -7.65632349 </eigenvalue_sum>
  <eigenvalue_sum>  -7.65912936 </eigenvalue_sum>
  <eigenvalue_sum>  -7.66246385 </eigenvalue_sum>
  <eigenvalue_sum>  -7.66499772 </eigenvalue_sum>
  <eigenvalue_sum>  -7.66580926 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60558   -21.49560   -14.48500   -14.20921   -14.20921
    -7.62712    -7.62712    -1.64762     1.74751     2.14389
     2.59109
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24758   -19.71241   -13.32899   -12.45856   -12.45856
    -5.52744    -5.52744    -1.58675     2.65111
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426104 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.36594841 -0.35231863 0.06873112 
  <eigenvalue_sum>  -7.66666186 </eigenvalue_sum>
  <eigenvalue_sum>  -7.66740000 </eigenvalue_sum>
  <eigenvalue_sum>  -7.66818689 </eigenvalue_sum>
  <eigenvalue_sum>  -7.66925894 </eigenvalue_sum>
  <eigenvalue_sum>  -7.67014419 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60570   -21.49571   -14.48511   -14.20932   -14.20932
    -7.62722    -7.62722    -1.66878     1.73568     2.14146
     2.54719
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24771   -19.71250   -13.32908   -12.45866   -12.45866
    -5.52754    -5.52754    -1.59474     2.62564
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426105 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.17396971 0.03672600 -0.10111685 
  <eigenvalue_sum>  -7.67081028 </eigenvalue_sum>
  <eigenvalue_sum>  -7.67143255 </eigenvalue_sum>
  <eigenvalue_sum>  -7.67203328 </eigenvalue_sum>
  <eigenvalue_sum>  -7.67269213 </eigenvalue_sum>
  <eigenvalue_sum>  -7.67333223 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60571   -21.49571   -14.48512   -14.20933   -14.20932
    -7.62723    -7.62722    -1.68710     1.73475     2.13921
     2.50830
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24771   -19.71250   -13.32908   -12.45867   -12.45867
    -5.52754    -5.52754    -1.60253     2.59994
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426105 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.23492616 -0.82347342 0.46518187 
  <eigenvalue_sum>  -7.67425891 </eigenvalue_sum>
  <eigenvalue_sum>  -7.67514140 </eigenvalue_sum>
  <eigenvalue_sum>  -7.67643610 </eigenvalue_sum>
  <eigenvalue_sum>  -7.67743905 </eigenvalue_sum>
  <eigenvalue_sum>  -7.67826672 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60570   -21.49570   -14.48511   -14.20932   -14.20932
    -7.62722    -7.62722    -1.71127     1.73393     2.13710
     2.43482
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24770   -19.71249   -13.32907   -12.45866   -12.45866
    -5.52754    -5.52753    -1.60785     2.57709
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426105 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.30628923 0.06946703 -0.27804953 
  <eigenvalue_sum>  -7.67899513 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68031421 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68141041 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68189508 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68231004 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60573   -21.49572   -14.48513   -14.20934   -14.20934
    -7.62724    -7.62724    -1.71543     1.73305     2.13496
     2.36319
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24773   -19.71250   -13.32908   -12.45868   -12.45868
    -5.52755    -5.52755    -1.61525     2.56221
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426105 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.13725009 0.11976297 -0.09127139 
  <eigenvalue_sum>  -7.68270764 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68321185 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68368718 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68510558 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68635999 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60574   -21.49573   -14.48513   -14.20935   -14.20935
    -7.62724    -7.62724    -1.71952     1.73066     2.13194
     2.34116
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24773   -19.71251   -13.32908   -12.45869   -12.45869
    -5.52756    -5.52755    -1.61971     2.48773
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426105 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.13602836 -0.20497555 0.06773475 
  <eigenvalue_sum>  -7.68676667 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68727639 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68768965 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68806437 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68840584 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60574   -21.49573   -14.48513   -14.20935   -14.20935
    -7.62724    -7.62724    -1.72338     1.72950     2.12477
     2.31360
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24773   -19.71251   -13.32908   -12.45869   -12.45869
    -5.52756    -5.52755    -1.62369     2.47785
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426105 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.26372902 0.12105596 -0.06582089 
  <eigenvalue_sum>  -7.68873738 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68911893 </eigenvalue_sum>
  <eigenvalue_sum>  -7.68949197 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69012238 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69071048 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60574   -21.49573   -14.48513   -14.20935   -14.20935
    -7.62724    -7.62724    -1.72613     1.72896     2.12384
     2.27937
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24773   -19.71250   -13.32908   -12.45869   -12.45868
    -5.52755    -5.52755    -1.64132     2.46935
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426105 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.28967106 -0.23348088 0.06914127 
  <eigenvalue_sum>  -7.69111056 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69189320 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69257636 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69352814 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69422747 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60574   -21.49572   -14.48513   -14.20935   -14.20935
    -7.62724    -7.62724    -1.72877     1.72834     2.12204
     2.20377
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24773   -19.71250   -13.32908   -12.45868   -12.45868
    -5.52755    -5.52755    -1.64212     2.45986
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426105 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = -0.36050283 -0.51998159 0.05404347 
  <eigenvalue_sum>  -7.69445146 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69467660 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69488007 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69505207 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69524117 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60574   -21.49572   -14.48513   -14.20935   -14.20935
    -7.62724    -7.62724    -1.73080     1.72750     2.12092
     2.19199
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24773   -19.71250   -13.32908   -12.45868   -12.45868
    -5.52755    -5.52755    -1.64303     2.45048
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426105 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 AndersonMixer: theta = 0.57497390 0.08505430 -0.28489707 
  <eigenvalue_sum>  -7.69541369 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69567534 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69591219 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69699955 </eigenvalue_sum>
  <eigenvalue_sum>  -7.69788425 </eigenvalue_sum>
<eigenset>
  <eigenvalues spin="0" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="11">
   -33.60574   -21.49573   -14.48513   -14.20935   -14.20935
    -7.62724    -7.62724    -1.73290     1.72707     2.11981
     2.18283
  </eigenvalues>
  <eigenvalues spin="1" kpoint="0.00000000 0.00000000 0.00000000" weight="1.00000000" n="9">
   -32.24773   -19.71250   -13.32908   -12.45869   -12.45869
    -5.52755    -5.52755    -1.64377     2.39007
  </eigenvalues>
</eigenset>
  <etotal_int>     -31.66426105 </etotal_int>
  BOSampleStepper: end scf iteration
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
  <ekin>        21.77074836 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -36.20634048 </eps>
  <enl>          4.29948148 </enl>
  <ecoul>      -14.90075214 </ecoul>
  <exc>         -6.62739827 </exc>
  <esr>          1.89222900 </esr>
  <eself>       19.14922946 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -31.66426105 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -31.66426105 </enthalpy>
<atomset>
<unit_cell 
    a=" 11.00000000   0.00000000   0.00000000"
    b="  0.00000000  11.00000000   0.00000000"
    c="  0.00000000   0.00000000  11.00000000" />
  <atom name="O1" species="oxygen">
    <position> 1.16000000 0.00000000 0.00000000 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.02130070 -0.00000008 0.00000003 </force>
  </atom>
  <atom name="O2" species="oxygen">
    <position> -1.16000000 0.00000000 0.00000000 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.02130071 0.00000003 0.00000003 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 11.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 11.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 11.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 1331.000 </unit_cell_volume>
  <timing name="iteration" min="   30.468" max="   30.477"/>
</iteration>
<timing name="         charge" min="    1.454" max="    1.629"/>
<timing name="         energy" min="   12.964" max="   12.973"/>
<timing name="      jd_blocks" min="    1.022" max="    1.027"/>
<timing name="   jd_compute_z" min="    0.606" max="    0.610"/>
<timing name="        jd_gemm" min="    0.416" max="    0.445"/>
<timing name="      jd_getsub" min="    0.050" max="    0.080"/>
<timing name="          jd_hz" min="   11.758" max="   11.766"/>
<timing name="    jd_residual" min="    0.182" max="    0.297"/>
<timing name="        jd_syev" min="    0.489" max="    0.493"/>
<timing name="    update_vhxc" min="    1.043" max="    1.065"/>
<timing name="      wf_update" min="   13.844" max="   13.980"/>
<timing name="         wfdiag" min="    0.079" max="    0.081"/>
<timing name="           ekin" min="    0.516" max="    0.540"/>
<timing name="            exc" min="    0.771" max="    0.788"/>
<timing name="           hpsi" min="   22.438" max="   22.481"/>
<timing name="       nonlocal" min="    1.676" max="    1.691"/>
<timing name=" charge_compute" min="    1.019" max="    1.132"/>
<timing name="charge_integral" min="    0.047" max="    0.134"/>
<timing name="  charge_rowsum" min="    0.025" max="    0.032"/>
<timing name="     charge_vft" min="    0.328" max="    0.344"/>
[qbox] <cmd>partial_charge O1 1.9</cmd>
 Atom O1 at 1.16000 0.00000 0.00000
 radius = 1.90000
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 <partial_charge atom="O1" radius="1.90000000"> 6.183851 </partial_charge>
<timing name=" charge_compute" min="    0.018" max="    0.019"/>
<timing name="charge_integral" min="    0.000" max="    0.002"/>
<timing name="  charge_rowsum" min="    0.001" max="    0.003"/>
<timing name="     charge_vft" min="    0.014" max="    0.015"/>
[qbox] <cmd>partial_charge -spin 1 O1 1.9</cmd>
 Atom O1 at 1.16000 0.00000 0.00000
 radius = 1.90000
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 <partial_charge atom="O1" radius="1.90000000" spin="1"> 3.563543 </partial_charge>
<timing name=" charge_compute" min="    0.025" max="    0.033"/>
<timing name="charge_integral" min="    0.001" max="    0.001"/>
<timing name="  charge_rowsum" min="    0.001" max="    0.001"/>
<timing name="     charge_vft" min="    0.007" max="    0.009"/>
[qbox] <cmd>partial_charge -spin 2 O1 1.9</cmd>
 Atom O1 at 1.16000 0.00000 0.00000
 radius = 1.90000
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 <partial_charge atom="O1" radius="1.90000000" spin="2"> 2.620309 </partial_charge>
<timing name=" charge_compute" min="    0.024" max="    0.026"/>
<timing name="charge_integral" min="    0.001" max="    0.002"/>
<timing name="  charge_rowsum" min="    0.001" max="    0.001"/>
<timing name="     charge_vft" min="    0.013" max="    0.015"/>
[qbox] <cmd>partial_charge O2 1.9</cmd>
 Atom O2 at -1.16000 0.00000 0.00000
 radius = 1.90000
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 <partial_charge atom="O2" radius="1.90000000"> 6.183851 </partial_charge>
<timing name=" charge_compute" min="    0.018" max="    0.024"/>
<timing name="charge_integral" min="    0.002" max="    0.009"/>
<timing name="  charge_rowsum" min="    0.001" max="    0.001"/>
<timing name="     charge_vft" min="    0.008" max="    0.008"/>
[qbox] <cmd>partial_charge -spin 1 O2 1.9</cmd>
 Atom O2 at -1.16000 0.00000 0.00000
 radius = 1.90000
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 <partial_charge atom="O2" radius="1.90000000" spin="1"> 3.563542 </partial_charge>
<timing name=" charge_compute" min="    0.019" max="    0.019"/>
<timing name="charge_integral" min="    0.001" max="    0.001"/>
<timing name="  charge_rowsum" min="    0.001" max="    0.001"/>
<timing name="     charge_vft" min="    0.014" max="    0.015"/>
[qbox] <cmd>partial_charge -spin 2 O2 1.9</cmd>
 Atom O2 at -1.16000 0.00000 0.00000
 radius = 1.90000
  total_electronic_charge: 7.00000000
  total_electronic_charge: 5.00000000
 <partial_charge atom="O2" radius="1.90000000" spin="2"> 2.620309 </partial_charge>
<timing name=" charge_compute" min="    0.024" max="    0.028"/>
<timing name="charge_integral" min="    0.001" max="    0.001"/>
<timing name="  charge_rowsum" min="    0.001" max="    0.001"/>
<timing name="     charge_vft" min="    0.008" max="    0.008"/>
[qbox] <cmd>save test.xml</cmd>
 SampleWriter: write time: 0.074 s
 SampleWriter: file size: 7264083
 SampleWriter: aggregate write rate: 93.40 MB/s
[qbox]  End of command stream 
<real_time> 31.00 </real_time>
<end_time> 2016-04-29T09:48:54Z </end_time>
</fpmd:simulation>
