12 0.00  0  NUMBER OF ORBITALS (EXCLUDING SPIN), SHIFT, IPRINT
1,-1,2               ( N,KAPPA,OCCUP)
2,-1,2               ( N,KAPPA,OCCUP)
2, 1,2               ( N,KAPPA,OCCUP)
2,-2,4               ( N,KAPPA,OCCUP)
3,-1,2               ( N,KAPPA,OCCUP)
3, 1,2               ( N,KAPPA,OCCUP)
3,-2,4               ( N,KAPPA,OCCUP)
3, 2,4               ( N,KAPPA,OCCUP)
3,-3,6               ( N,KAPPA,OCCUP)
4,-1,2               ( N,KAPPA,OCCUP)
4, 1,2               ( N,KAPPA,OCCUP)
4,-2,4               ( N,KAPPA,OCCUP)
 4 0.00  0  NUMBER OF ORBITALS (EXCLUDING SPIN), SHIFT, IPRINT
1,-1,2               ( N,KAPPA,OCCUP)
2,-1,2               ( N,KAPPA,OCCUP)
2, 1,2               ( N,KAPPA,OCCUP)
2,-2,4               ( N,KAPPA,OCCUP)
 1 0.00  0  NUMBER OF ORBITALS (EXCLUDING SPIN), SHIFT, IPRINT
1,-1,2               ( N,KAPPA,OCCUP)
 0
